import { Helmet } from "react-helmet-async";

const products = [
  { id:"vinyl", title:"Personalised 12-Inch Vinyl Record", description:"Your personalised song, preserved on a full-size 12-inch record with bespoke sleeve and label artwork.", price:"£99 + delivery", note:"One record. Two playable sides. Made individually for your story." },
  { id:"artwork", title:"Framed Lyric Artwork", description:"Timeless typography and personal artwork designed to make your story part of your home.", price:"Made to order", note:"Available as a personalised enhancement to your MCB experience." },
  { id:"plaque", title:"Engraved Music Plaques", description:"Crystal or wood with a scannable code to your song.", price:"Made to order", note:"Personalised around your song, message and artwork." },
  { id:"memory-box", title:"Luxury Memory Boxes", description:"Lyrics, photos, and your song in one complete experience.", price:"Made to order", note:"Curated individually to suit your story and presentation." },
  { id:"cards", title:"Premium Music Cards", description:"A beautiful personalised card that connects the moment to your song.", price:"Made to order", note:"Selected designs available for celebrations, journeys and meaningful gifts." }
];

const Products=()=> <><Helmet><title>Custom Vinyl & Music Keepsakes | My Custom Beats</title><meta name="description" content="Turn your personalised song into a luxury 12-inch vinyl record, Journey Collection, framed artwork, music card or bespoke memory keepsake."/></Helmet><div className="bg-[#FBF9F6] text-black">
<section className="relative min-h-[90vh] flex items-center justify-center overflow-hidden"><div className="absolute inset-0 overflow-hidden"><video className="w-full h-full object-cover scale-[1.05] animate-heroZoom" autoPlay loop muted playsInline preload="none" poster="/images/products-poster.jpg"><source src="/videos/products.mp4" type="video/mp4"/></video></div><div className="absolute inset-0 bg-gradient-to-t from-espresso/80 via-espresso/50 to-espresso/30 backdrop-blur-[2px]"/><div className="relative z-10 text-center px-6"><span className="label-uppercase text-ivory/60 mb-6 tracking-[0.2em]">Luxury Keepsakes • Crafted to Last Forever</span><h1 className="font-serif text-ivory mb-8 max-w-4xl leading-[1.05]" style={{fontSize:'clamp(2.5rem, 6vw, 4.5rem)'}}>Turn your song into something you can hold forever</h1><p className="text-xl text-ivory/85 max-w-2xl mx-auto leading-relaxed">A song carries emotion. We transform it into a physical piece you can see, touch and relive forever.</p></div></section>
<section className="px-6 max-w-6xl mx-auto py-20 space-y-24">{products.map(product=><div key={product.id} className="grid md:grid-cols-2 gap-12 items-center"><div className="h-[400px] rounded-2xl overflow-hidden bg-white shadow-sm hover:shadow-xl transition duration-500"><img src={`/images/products/${product.id}.jpg`} alt={product.title} loading="lazy" decoding="async" className="w-full h-full object-cover transition duration-700"/></div><div><h2 className="text-3xl md:text-4xl font-light mb-4">{product.title}</h2><p className="text-black/60 mb-5 leading-relaxed">{product.description}</p><p className="font-serif text-2xl text-gold mb-2">{product.price}</p><p className="text-sm text-black/50">{product.note}</p>{product.id==='vinyl'&&<p className="text-xs text-black/45 mt-4">MCB vinyl keepsakes are supplied exclusively as 12-inch records. Personalised production and delivery times apply.</p>}</div></div>)}</section>
<section className="py-24 px-6 bg-espresso text-ivory"><div className="max-w-6xl mx-auto"><div className="max-w-3xl mx-auto text-center mb-14"><p className="label-uppercase text-gold mb-4">The MCB Journey Collection</p><h2 className="font-serif text-4xl md:text-5xl mb-6">Preserve every day of your journey.</h2><p className="text-ivory/75 text-lg leading-relaxed">Every day of a cruise or holiday can become its own personalised MCB Keepsake. Choose every day, or simply select the days and experiences that mean the most to you. Each chosen day is £99 and becomes part of one coordinated collection.</p></div><div className="max-w-4xl mx-auto grid md:grid-cols-3 gap-6"><div className="border border-gold/25 rounded-2xl p-7 bg-white/5"><p className="font-serif text-3xl text-gold mb-3">£99</p><p className="text-ivory/85">Per chosen day</p><p className="text-sm text-ivory/60 mt-3">One day. One story. One individual Keepsake.</p></div><div className="border border-gold/25 rounded-2xl p-7 bg-white/5"><p className="font-serif text-3xl text-gold mb-3">£297</p><p className="text-ivory/85">Example: 3 chosen days</p><p className="text-sm text-ivory/60 mt-3">Three individual Keepsakes in one coordinated collection.</p></div><div className="border border-gold/25 rounded-2xl p-7 bg-white/5"><p className="font-serif text-3xl text-gold mb-3">£693</p><p className="text-ivory/85">Example: 7 chosen days</p><p className="text-sm text-ivory/60 mt-3">A seven-day cruise can become seven individual Keepsakes.</p></div></div><div className="max-w-3xl mx-auto text-center mt-12"><p className="text-ivory/70 leading-relaxed">There is no fixed bundle and no artificial maximum. A 14-day cruise can become 14 Keepsakes, or you can preserve only the days you care about. Designed to display together on your wall or build into your personal record collection.</p><a href="/#order" className="inline-flex mt-8 items-center px-8 py-3 bg-gold text-espresso rounded-full font-medium transition-all duration-300 hover:bg-ivory hover:scale-105">Create Your Journey Collection</a></div></div></section>
<section className="py-24 px-6 bg-white"><div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-12 items-center"><div><p className="label-uppercase text-gold mb-4">Play & Display</p><h2 className="font-serif text-4xl mb-6">Your records belong on the wall — and on the turntable.</h2><p className="text-black/60 leading-relaxed mb-5">Add a 12-inch Play & Display frame for the vinyl records in your MCB collection. Buy a single frame or build a coordinated wall display as your collection grows.</p><p className="font-serif text-2xl text-gold">£60 single • £150 set of three</p><p className="text-sm text-black/50 mt-3">When purchasing vinyl keepsakes, you can add frames to suit the number of records in your order.</p></div><div className="rounded-2xl border border-black/10 bg-[#FBF9F6] p-8"><h3 className="font-serif text-2xl mb-5">Designed around your collection</h3><ul className="space-y-3 text-black/65"><li>• Fits standard 12-inch record sleeves</li><li>• Add one frame for an individual Keepsake</li><li>• Add sets of three for a growing wall collection</li><li>• Mix singles and sets to suit your vinyl quantity</li></ul></div></div></section>
<section className="py-24 px-6 bg-[#FBF9F6]"><div className="max-w-4xl mx-auto text-center"><p className="label-uppercase text-gold mb-4">MCB Gift Experience</p><h2 className="font-serif text-4xl mb-6">Give the story now. Let them create it when they’re ready.</h2><p className="text-black/60 leading-relaxed">Purchase an MCB digital gift voucher for future use. The recipient can return to My Custom Beats when the right moment arrives and redeem their unique code toward their MCB experience.</p><p className="text-sm text-black/50 mt-5">Voucher terms: expiry date applies. No transfer. No refunds. No cash redemption.</p></div></section>
<section className="py-24 px-6 bg-white"><div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-12 items-center"><div><p className="label-uppercase text-gold mb-4">The MCB Story Album™</p><h2 className="font-serif text-4xl mb-6">Two records. Four sides. One extraordinary story.</h2><p className="text-black/60 leading-relaxed mb-5">For stories that deserve a larger canvas, the MCB Story Album transforms your personalised music collection into a deluxe double 12-inch vinyl experience with up to four playable sides and a fully personalised gatefold presentation.</p><p className="font-serif text-2xl text-gold mt-6">From £279 + delivery</p></div><div className="rounded-2xl border border-black/10 bg-[#FBF9F6] p-8"><h3 className="font-serif text-2xl mb-5">Personalise the complete story</h3><ul className="space-y-3 text-black/65"><li>• Two full-size 12-inch records</li><li>• Four playable sides</li><li>• Personalised gatefold artwork</li><li>• Your photographs, dates and destinations</li><li>• Personalised centre labels and track listing</li></ul></div></div></section>
<section className="text-center py-32 px-6 border-t border-black/10"><h2 className="text-4xl font-light mb-6">Create Something They’ll Never Forget</h2><p className="text-black/60 max-w-xl mx-auto mb-10">Start with your story. We’ll bring it to life.</p><a href="/#order" className="inline-flex items-center gap-3 px-8 py-3 bg-gold text-espresso rounded-full font-medium transition-all duration-300 hover:bg-espresso hover:text-ivory hover:scale-105 shadow-md hover:shadow-xl">Begin Your Story</a></section>
</div></>;
export default Products;
